server:
  port: 9001

spring:
  application:
    name:  boot-rabbitMq
  rabbitmq:
    host: 112.74.43.136
    port: 5672
    username: cat
    password: cat
    publisher-confirms: true #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true  # 交换机发送消息给队列返回确认
    ##开启ack
    listener:
      direct:
      ## 采取手动应答
        acknowledge-mode: manual
        ## 批量一次性接收多少条数据
        prefetch:  10
      simple:
        acknowledge-mode: manual
